#ifndef __INTROSPECTION_XML__
#define __INTROSPECTION_XML__

const gchar introspection_xml[] =
"<node>"
"<interface name='org.freedesktop.MediaPlayer'>"
"    <method name='Identity'>"
"        <arg type='s' direction='out'/>"
"    </method>"
"    <method name='Quit'>"
"    </method>"
"    <method name='MprisVersion'>"
"        <arg type='(qq)' direction='out'/>"
"    </method>"
"    <method name='GetMetadata'>"
"        <arg type='i' direction='in' />"
"        <arg type='a{sv}' direction='out' />"
"    </method>"
"    <method name='GetCurrentTrack'>"
"        <arg type='i' direction='out' />"
"    </method>"
"    <method name='GetLength'>"
"        <arg type='i' direction='out' />"
"    </method>"
"    <method name='AddTrack'>"
"        <arg type='s' direction='in' />"
"        <arg type='b' direction='in' />"
"        <arg type='i' direction='out' />"
"    </method>"
"    <method name='DelTrack'>"
"        <arg type='i' />"
"    </method>"
"    <method name='SetLoop'>"
"        <arg type='b' />"
"    </method>"
"    <method name='SetRandom'>"
"        <arg type='b' />"
"    </method>"
"    <method name='Next'>"
"    </method>"
"    <method name='Prev'>"
"    </method>"
"    <method name='Pause'>"
"    </method>"
"    <method name='Stop'>"
"    </method>"
"    <method name='Play'>"
"    </method>"
"    <method name='Repeat'>"
"        <arg type='b' />"
"    </method>"
"    <method name='GetStatus'>"
"        <arg type='(iiii)' direction='out'/>"
"    </method>"
"    <method name='GetMetadata'>"
"        <arg type='a{sv}' direction='out' />"
"    </method>"
"    <method name='GetCaps'>"
"        <arg type='i' direction='out' />"
"    </method>"
"    <signal name='CapsChange'>"
"        <arg type='i' />"
"    </signal>"
"    <method name='VolumeSet'>"
"        <arg type='i'/>"
"    </method>"
"    <method name='VolumeGet'>"
"        <arg type='i' direction='out'/>"
"    </method>"
"    <method name='PositionSet'>"
"        <arg type='i'/>"
"    </method>"
"    <method name='PositionGet'>"
"        <arg type='i' direction='out'/>"
"    </method>"
"    <signal name='TrackChange'>"
"        <arg type='a{sv}'/>"
"    </signal>"
"    <signal name='StatusChange'>"
"        <arg type='(iiii)'/>"
"    </signal>"
"    <signal name='CapsChange'>"
"        <arg type='i' />"
"    </signal>"
"    <signal name='TrackListChange'>"
"        <arg type='i' />"
"    </signal>  "
"</interface>"
"</node>";

#endif
